config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "fabricantes#index"

  resources :fabricantes do
  	resources :produtos
  end

  resources :events, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/produtos_controller.rb
require 'net/http'
require 'json'

class ProdutosController < ApplicationController
  before_action :load_produtos_list, only: [:new]
  before_action :set_produto, only: [:show, :edit, :update, :destroy]
  before_action :load_fabricante

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = @fabricante.produtos.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    old_produto = Produto.new
    @produto = @fabricante.produtos.build produto_params

    respond_to do |format|
      if @produto.save
        store_changes old_produto, @produto
        format.html { redirect_to fabricante_produto_path(@fabricante, @produto), notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    old_produto = Produto.new @produto.attributes

    respond_to do |format|
      if @produto.update(produto_params)
        store_changes old_produto, @produto
        format.html { redirect_to fabricante_produto_path(@fabricante, @produto), notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to fabricante_produtos_path(@fabricante), notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def load_produtos_list
      @produtos_from_service = []

      url = URI.parse('http://produtos.g.schiar.vms.ufsc.br:3000/products.json')
      req = Net::HTTP::Get.new(url.to_s)
      req.basic_auth 'giovani@schiar.com', 'lalala'
      res = Net::HTTP.start(url.host, url.port) {|http|
        http.request(req)
      } rescue nil

      if(res == nil)
        @produtos_from_service = nil;
      else
        JSON.parse(res.body).each do |produto_s|
          @produtos_from_service.push Produto.new({id:produto_s['id'], nome: produto_s['name'], codigo: produto_s['code']})
        end
      end
    end

    def load_fabricante
      @fabricante = Fabricante.find(params[:fabricante_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
      puts '-' * 100
      puts @produto.inspect
      puts '-' * 100
    end

    def set_produto_from_service
      @produto = @produtos_from_service.detect {|item| params[:id].to_i == item.id}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :codigo, :price, :fabricante_id)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for @produto, url: fabricante_produto_path(@fabricante, @produto) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :produto_nome, :disabled => true %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo, id: :produto_codigo, :disabled => true %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :produto_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', fabricante_produto_path(@fabricante, @produto) %> |
<%= link_to 'Back', fabricante_produtos_path(@fabricante)  %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos do fabricante <%=@fabricante.nome%></h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fabricante.produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.codigo %></td>
        <td><%= produto.price %></td>
        <td><%= link_to 'Show', fabricante_produto_path(@fabricante, produto) %></td>
        <td><%= link_to 'Edit', edit_fabricante_produto_path(@fabricante, produto) %></td>
        <td><%= link_to 'Destroy', fabricante_produto_path(@fabricante, produto), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Adicionar Produto', new_fabricante_produto_path %> |
<%= link_to 'Back', fabricante_path(@fabricante) %>

app/views/produtos/new.html.erb
<% if @produtos_from_service == nil %>
  <h1>Serviço indisponivel temporariamente</h1>
<% else %>
  <h1>New Produto</h1>

  <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Codigo</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @produtos_from_service.each do |produto| %>
        <tr>
          <td><%= produto.nome %></td>
          <td><%= produto.codigo %></td>
          <td><%= link_to "Selecionar", fabricante_produtos_path(@fabricante, produto: {nome: produto.nome, codigo: produto.codigo}), method: :post %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'Back', fabricantes_path(@fabricante) %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @produto.codigo %>
</p>

<p>
  <strong>Preço:</strong>
  <%= number_to_currency(@produto.price) %>
</p>


<%= link_to 'Back', fabricante_produtos_path %>