config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "fabricantes#index"

  resources :fabricantes do
  	resources :produtos
  end

  resources :events, only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fabricante.rb
class Fabricante < ApplicationRecord
  has_many :produtos
  validates_uniqueness_of :codigo
end

app/controllers/fabricantes_controller.rb
class FabricantesController < ApplicationController
  before_action :set_fabricante, only: [:show, :edit, :update, :destroy]

  # GET /fabricantes
  # GET /fabricantes.json
  def index
    @fabricantes = Fabricante.all
  end

  # GET /fabricantes/1
  # GET /fabricantes/1.json
  def show
  end

  # GET /fabricantes/new
  def new
    @fabricante = Fabricante.new
  end

  # GET /fabricantes/1/edit
  def edit
  end

  # POST /fabricantes
  # POST /fabricantes.json
  def create
    old_fabricante = Fabricante.new
    @fabricante = Fabricante.new(fabricante_params)

    respond_to do |format|
      if @fabricante.save
        store_changes(old_fabricante, @fabricante)
        format.html { redirect_to @fabricante, notice: 'Fabricante was successfully created.' }
        format.json { render :show, status: :created, location: @fabricante }
      else
        format.html { render :new }
        format.json { render json: @fabricante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fabricantes/1
  # PATCH/PUT /fabricantes/1.json
  def update
    old_fabricante = Fabricante.new @fabricante.attributes
    
    respond_to do |format|
      if @fabricante.update(fabricante_params)
        store_changes(old_fabricante, @fabricante)
        format.html { redirect_to @fabricante, notice: 'Fabricante was successfully updated.' }
        format.json { render :show, status: :ok, location: @fabricante }
      else
        format.html { render :edit }
        format.json { render json: @fabricante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fabricantes/1
  # DELETE /fabricantes/1.json
  def destroy
    @fabricante.destroy
    respond_to do |format|
      format.html { redirect_to fabricantes_url, notice: 'Fabricante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fabricante
      @fabricante = Fabricante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fabricante_params
      params.require(:fabricante).permit(:nome, :codigo)
    end
end

app/helpers/fabricantes_helper.rb
module FabricantesHelper
end

app/views/fabricantes/_form.html.erb
<%= form_with(model: fabricante, local: true) do |form| %>
  <% if fabricante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fabricante.errors.count, "error") %> prohibited this fabricante from being saved:</h2>

      <ul>
      <% fabricante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :fabricante_nome %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.number_field :codigo, id: :fabricante_codigo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fabricantes/edit.html.erb
<h1>Editing Fabricante</h1>

<%= render 'form', fabricante: @fabricante %>

<%= link_to 'Show', @fabricante %> |
<%= link_to 'Back', fabricantes_path %>

app/views/fabricantes/index.html.erb
<div>
  Welcome <%= current_user.email %>!
  <%= link_to 'logout', destroy_user_session_path, method: 'delete' %>
</div>

<p id="notice"><%= notice %></p>

<h1>Fabricantes <small><%= link_to "logs", events_path %></small> </h1> 

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fabricantes.each do |fabricante| %>
      <tr>
        <td><%= fabricante.nome %></td>
        <td><%= fabricante.codigo %></td>
        <td><%= link_to 'Show', fabricante %></td>
        <td><%= link_to 'Edit', edit_fabricante_path(fabricante) %></td>
        <td><%= link_to 'Destroy', fabricante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fabricante', new_fabricante_path %>

app/views/fabricantes/new.html.erb
<h1>New Fabricante</h1>

<%= render 'form', fabricante: @fabricante %>

<%= link_to 'Back', fabricantes_path %>

app/views/fabricantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @fabricante.nome %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @fabricante.codigo %>
</p>

<p>
  <strong><%= link_to 'Produtos', fabricante_produtos_path(@fabricante) %></strong>
</p>

<%= link_to 'Edit', edit_fabricante_path(@fabricante) %> |
<%= link_to 'Back', fabricantes_path %>